### ISSUE TITLE
Add ability to toggle stream state.

### ISSUE THREAD

**Issue by nickvanhouten** [bitfocus/companion-module-bmd-webpresenterhd#6] opened 2022-08-12 01:45 UTC
Could a third stream control option be added, "Toggle"

**Comment by daniep01** [comment] 2022-08-12 08:28
I have added this option but I am unable to test it on the hardware until next week. Let me know if you would like a build to test yourself (or alternatively you can build from source).

**Comment by nickvanhouten** [comment] 2022-08-12 08:29
If you wouldn’t mind, that would be great! I will have hardware in front of me on Sunday.Sincerely,Nick Van Houten | NVH Design(626) ***@***.*** Aug 12, 2022, at 01:28, Peter ***@***.***> wrote:﻿
I have added this option but I am unable to test it on the hardware until next week. Let me know if you would like a build to test yourself (or alternatively you can build from source).

**Comment by daniep01** [comment] 2022-08-12 09:39
I have made a test build with webpresenter 1.0.6. Please be careful if using this build on a live production as it may upgrade or downgrade other modules you use. Hopefully it works as intended, please let me know either way.

[https://we.tl/t-RzuQDj7fGM](https://we.tl/t-RzuQDj7fGM)

**Comment by nickvanhouten** [comment] 2022-08-14 18:32
Shoot, can you make a Mac build?Thanks. Sincerely,Nick Van Houten | NVH Design(626) ***@***.*** Aug 12, 2022, at 02:40, Peter ***@***.***> wrote:﻿
I have made a test build with webpresenter 1.0.6. Please be careful if using this build on a live production as it may upgrade or downgrade other modules you use. Hopefully it works as intended, please let me know either way.
https://we.tl/t-RzuQDj7fGM

**Comment by daniep01** [comment] 2022-08-16 18:56
I have tested this myself today and it all seems to be working so it will be in a Companion beta release soon.

**Closed** 2022-08-18 20:26 UTC
Labels: enhancement

**Comment by nickvanhouten** [comment] 2022-10-30 18:21
Hi there,Did this get folded into the official release? I had someone update companion on my machine and I lost these functions...Thanks!-Nick VanHoutenOn Aug 14, 2022, at 11:31 AM, Nicholas Van Houten ***@***.***> wrote:Shoot, can you make a Mac build?Thanks. Sincerely,Nick Van Houten | NVH Design(626) ***@***.*** Aug 12, 2022, at 02:40, Peter ***@***.***> wrote:﻿I have made a test build with webpresenter 1.0.6. Please be careful if using this build on a live production as it may upgrade or downgrade other modules you use. Hopefully it works as intended, please let me know either way.https://we.tl/t-RzuQDj7fGM—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by daniep01** [comment] 2022-10-30 21:53
You need version 1.0.6 of the WebPresenter module.
